CREATE TABLE myCustomTable (
    myIntValue                  integer         null ,
    myIntegerNullableValue      integer         null ,
    myLongValue                 integer         null ,
    myLongNullableValue         integer         null ,
    myFloatValue                float           null ,
    myFloatNullableValue        float           null ,
    myDoubleValue               float           null ,
    myDoubleNullableValue       float           null ,
    myBooleanValue              integer         null ,
    myBooleanNullableValue      integer         null ,
    myDate                      integer         null ,
    myDateNullable              integer         null ,
    myString                    nvarchar        null ,
    myStringNoSelect            nvarchar        null ,
    myStringNoInsert            nvarchar        null );

CREATE TABLE DbEntityTest (
    _id                         integer         primary key autoincrement ,
    dateCreate                  integer         null ,
    dateModification            integer         null ,

    intValue                    integer         null ,
    integerNullableValue        integer         null ,
    longValue                   integer         null ,
    longNullableValue           integer         null ,
    floatValue                  float           null ,
    floatNullableValue          float           null ,
    doubleValue                 float           null ,
    doubleNullableValue         float           null ,
    booleanValue                boolean         null ,
    booleanNullableValue        boolean         null ,
    date                        integer         null ,
    dateNullable                integer         null ,
    myString                    nvarchar        null ,
    myMyCustomColumnName        nvarchar        null ,
    stringNoSelect              nvarchar        null ,
    stringNoInsert              nvarchar        null );

CREATE TABLE DbEntityServerTest (
    _id                         integer         primary key autoincrement ,
    dateCreate                  integer         null ,
    dateModification            integer         null ,
    idServer                    nvarchar        null ,
    isSent                      boolean         null ,
    dateUtcSent                 integer         null ,

    intValue                    integer         null ,
    integerNullableValue        integer         null ,
    longValue                   integer         null ,
    longNullableValue           integer         null ,
    floatValue                  float           null ,
    floatNullableValue          float           null ,
    doubleValue                 float           null ,
    doubleNullableValue         float           null ,
    booleanValue                integer         null ,
    booleanNullableValue        integer         null ,
    date                        integer         null ,
    dateNullable                integer         null ,
    myString                    nvarchar        null ,
    myMyCustomColumnName        nvarchar        null ,
    stringNoSelect              nvarchar        null ,
    stringNoInsert              nvarchar        null  );

